// lib/constants/taxonomy.ts

export const CATEGORIES = [
  {
    slug: "shoes",
    label: "Shoes",
    subcategories: [
      { slug: "sneakers-athletic", label: "Sneakers & Athletic" },
      { slug: "boots-booties", label: "Boots & Booties" },
      { slug: "sandals-flip-flops", label: "Sandals & Flip-Flops" },
      { slug: "heels", label: "Heels" },
      { slug: "flats-loafers", label: "Flats & Loafers" },
      { slug: "dress-shoes-oxfords", label: "Dress Shoes & Oxfords" },
      { slug: "slippers", label: "Slippers" },
    ],
  },
  {
    slug: "clothing",
    label: "Clothing",
    subcategories: [
      { slug: "tops-tshirts", label: "Tops & T-Shirts" },
      { slug: "sweatshirts-hoodies", label: "Sweatshirts & Hoodies" },
      { slug: "sweaters", label: "Sweaters" },
      { slug: "dresses", label: "Dresses" },
      { slug: "jeans-pants", label: "Jeans & Pants" },
      { slug: "activewear", label: "Activewear" },
      { slug: "coats-jackets", label: "Coats & Jackets" },
      { slug: "suits-blazers", label: "Suits & Blazers" },
      { slug: "sleepwear-loungewear", label: "Sleepwear & Loungewear" },
      { slug: "swimwear", label: "Swimwear" },
    ],
  },
  {
    slug: "accessories",
    label: "Accessories",
    subcategories: [
      { slug: "handbags-wallets-backpacks", label: "Handbags, Wallets & Backpacks" },
      { slug: "luggage-travel", label: "Luggage & Travel" },
      { slug: "jewelry", label: "Jewelry" },
      { slug: "watches", label: "Watches" },
      { slug: "belts", label: "Belts" },
      { slug: "sunglasses", label: "Sunglasses" },
      { slug: "hats-gloves-scarves", label: "Hats, Gloves & Scarves" },
    ],
  },
  {
    slug: "beauty",
    label: "Beauty",
    subcategories: [
      { slug: "skincare", label: "Skincare" },
      { slug: "makeup", label: "Makeup" },
      { slug: "fragrance", label: "Fragrance" },
      { slug: "hair-care", label: "Hair Care" },
      { slug: "grooming", label: "Grooming" },
    ],
  },
  {
    slug: "home",
    label: "Home",
    subcategories: [
      { slug: "bedding", label: "Bedding" },
      { slug: "bath", label: "Bath" },
      { slug: "kitchen-dining", label: "Kitchen & Dining" },
      { slug: "furniture", label: "Furniture" },
      { slug: "decor", label: "Decor" },
    ],
  },
  {
    slug: "gifts",
    label: "Gifts",
    subcategories: [
      { slug: "gift-sets", label: "Gift Sets" },
      { slug: "gift-cards", label: "Gift Cards" },
      { slug: "stocking-stuffers", label: "Stocking Stuffers" },
      { slug: "gifts-under-25", label: "Gifts Under $25" },
      { slug: "gifts-under-50", label: "Gifts Under $50" },
    ],
  },
] as const;

export const GENDERS = [
  { slug: "men", label: "Men" },
  { slug: "women", label: "Women" },
  { slug: "kids", label: "Kids" },
  { slug: "unisex", label: "Unisex" },
] as const;

export const BRANDS = [
  { slug: "nike", label: "Nike" },
  { slug: "adidas", label: "Adidas" },
  { slug: "new-balance", label: "New Balance" },
  { slug: "skechers", label: "Skechers" },
  { slug: "converse", label: "Converse" },
  { slug: "vans", label: "Vans" },
  { slug: "puma", label: "Puma" },
  { slug: "under-armour", label: "Under Armour" },
  { slug: "reebok", label: "Reebok" },
  { slug: "levis", label: "Levi's" },
  { slug: "calvin-klein", label: "Calvin Klein" },
  { slug: "tommy-hilfiger", label: "Tommy Hilfiger" },
  { slug: "ralph-lauren", label: "Ralph Lauren" },
  { slug: "the-north-face", label: "The North Face" },
  { slug: "champion", label: "Champion" },
  { slug: "columbia", label: "Columbia" },
  { slug: "coach", label: "Coach" },
  { slug: "michael-kors", label: "Michael Kors" },
  { slug: "kate-spade", label: "Kate Spade" },
  { slug: "fossil", label: "Fossil" },
  { slug: "guess", label: "Guess" },
  { slug: "hm", label: "H&M" },
  { slug: "mango", label: "Mango" },
  { slug: "dockers", label: "Dockers" },
  { slug: "steve-madden", label: "Steve Madden" },
  { slug: "timberland", label: "Timberland" },
  { slug: "crocs", label: "Crocs" },
  { slug: "ugg", label: "UGG" },
  { slug: "amazfit", label: "Amazfit" },
  { slug: "vionic", label: "Vionic" },
  { slug: "birkenstock", label: "Birkenstock" },
  { slug: "carolina-herrera", label: "Carolina Herrera" },
  { slug: "brixton", label: "Brixton" },
  { slug: "giuseppe-zanotti", label: "Giuseppe Zanotti" },
  { slug: "rowe-and-taylor", label: "Rowe and Taylor" },
  { slug: "bloomingdales", label: "Bloomingdale's" },
  { slug: "tory-burch", label: "Tory Burch" },
  { slug: "maceoo", label: "Maceoo" },
  { slug: "vy-jewelry", label: "VY Jewelry" },
  { slug: "oakley", label: "Oakley" },
  { slug: "ray-ban", label: "Ray-Ban" },
  { slug: "costa-del-mar", label: "Costa Del Mar" },
  { slug: "tucci", label: "TUCCI" },
  { slug: "bvlgari", label: "Bvlgari" },
  { slug: "lancome", label: "Lancôme" },
  { slug: "sachin-and-babi", label: "Sachin and Babi" },
  { slug: "dream-pairs", label: "Dream Pairs" },
  { slug: "nortiv-8", label: "Nortiv 8" },
  { slug: "bruno-marc", label: "Bruno Marc" },
  { slug: "coofandy", label: "Coofandy" },
  { slug: "kxkshop", label: "KXKshop" },
  { slug: "crazy-shirts", label: "Crazy Shirts" }, 
  { slug: "ecko-unltd", label: "Ecko Unltd" }, 
  { slug: "musinsa", label: "Musinsa" },
  { slug: "dancewear-solutions", label: "Dancewear Solutions" },
  { slug: "marathon-watch", label: "Marathon Watch" },
  { slug: "belle-fare", label: "Belle Fare" },
  { slug: "citizen", label: "Citizen" },
  { slug: "gevril", label: "Gevril" },
  { slug: "hamilton", label: "Hamilton" },
  { slug: "mido", label: "Mido" },
  { slug: "tissot", label: "Tissot" },
  { slug: "zodiac", label: "Zodiac" },
  { slug: "certina", label: "Certina" },
  { slug: "ball", label: "Ball" },
  { slug: "longines", label: "Longines" },
  { slug: "dansko", label: "Dansko" },
  { slug: "ecco", label: "Ecco" },
  { slug: "abeo", label: "ABEO" },
  { slug: "clarks", label: "Clarks" },

] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];
export type GenderSlug = (typeof GENDERS)[number]["slug"];
export type BrandSlug = (typeof BRANDS)[number]["slug"];

export function getSubcategories(categorySlug: string) {
  return CATEGORIES.find((c) => c.slug === categorySlug)?.subcategories ?? [];
}