// lib/constants/taxonomy.ts

export const CATEGORIES = [
  {
    slug: "shoes",
    label: "Shoes",
    subcategories: [
      { slug: "sneakers-athletic", label: "Sneakers & Athletic" },
      { slug: "boots-booties", label: "Boots & Booties" },
      { slug: "sandals-flip-flops", label: "Sandals & Flip-Flops" },
      { slug: "heels", label: "Heels" },
      { slug: "flats-loafers", label: "Flats & Loafers" },
      { slug: "dress-shoes-oxfords", label: "Dress Shoes & Oxfords" },
      { slug: "slippers", label: "Slippers" },
    ],
  },
  {
    slug: "clothing",
    label: "Clothing",
    subcategories: [
      { slug: "tops-tshirts", label: "Tops & T-Shirts" },
      { slug: "sweatshirts-hoodies", label: "Sweatshirts & Hoodies" },
      { slug: "sweaters", label: "Sweaters" },
      { slug: "dresses", label: "Dresses" },
      { slug: "jeans-pants", label: "Jeans & Pants" },
      { slug: "activewear", label: "Activewear" },
      { slug: "coats-jackets", label: "Coats & Jackets" },
      { slug: "suits-blazers", label: "Suits & Blazers" },
      { slug: "sleepwear-loungewear", label: "Sleepwear & Loungewear" },
      { slug: "swimwear", label: "Swimwear" },
    ],
  },
  {
    slug: "accessories",
    label: "Accessories",
    subcategories: [
      { slug: "handbags-wallets-backpacks", label: "Handbags, Wallets & Backpacks" },
      { slug: "luggage-travel", label: "Luggage & Travel" },
      { slug: "jewelry", label: "Jewelry" },
      { slug: "watches", label: "Watches" },
      { slug: "belts", label: "Belts" },
      { slug: "sunglasses", label: "Sunglasses" },
      { slug: "hats-gloves-scarves", label: "Hats, Gloves & Scarves" },
    ],
  },
  {
    slug: "beauty",
    label: "Beauty",
    subcategories: [
      { slug: "skincare", label: "Skincare" },
      { slug: "makeup", label: "Makeup" },
      { slug: "fragrance", label: "Fragrance" },
      { slug: "hair-care", label: "Hair Care" },
      { slug: "grooming", label: "Grooming" },
    ],
  },
  {
    slug: "home",
    label: "Home",
    subcategories: [
      { slug: "bedding", label: "Bedding" },
      { slug: "bath", label: "Bath" },
      { slug: "kitchen-dining", label: "Kitchen & Dining" },
      { slug: "furniture", label: "Furniture" },
      { slug: "decor", label: "Decor" },
    ],
  },
  {
    slug: "gifts",
    label: "Gifts",
    subcategories: [
      { slug: "gift-sets", label: "Gift Sets" },
      { slug: "gift-cards", label: "Gift Cards" },
      { slug: "stocking-stuffers", label: "Stocking Stuffers" },
      { slug: "gifts-under-25", label: "Gifts Under $25" },
      { slug: "gifts-under-50", label: "Gifts Under $50" },
    ],
  },
] as const;

export const GENDERS = [
  { slug: "men", label: "Men" },
  { slug: "women", label: "Women" },
  { slug: "kids", label: "Kids" },
  { slug: "unisex", label: "Unisex" },
] as const;

export const BRANDS = [
  { slug: "nike", label: "Nike" },
  { slug: "adidas", label: "Adidas" },
  { slug: "new-balance", label: "New Balance" },
  { slug: "skechers", label: "Skechers" },
  { slug: "converse", label: "Converse" },
  { slug: "vans", label: "Vans" },
  { slug: "puma", label: "Puma" },
  { slug: "under-armour", label: "Under Armour" },
  { slug: "reebok", label: "Reebok" },
  { slug: "levis", label: "Levi's" },
  { slug: "calvin-klein", label: "Calvin Klein" },
  { slug: "tommy-hilfiger", label: "Tommy Hilfiger" },
  { slug: "ralph-lauren", label: "Ralph Lauren" },
  { slug: "the-north-face", label: "The North Face" },
  { slug: "champion", label: "Champion" },
  { slug: "columbia", label: "Columbia" },
  { slug: "coach", label: "Coach" },
  { slug: "michael-kors", label: "Michael Kors" },
  { slug: "kate-spade", label: "Kate Spade" },
  { slug: "fossil", label: "Fossil" },
  { slug: "guess", label: "Guess" },
  { slug: "hm", label: "H&M" },
  { slug: "mango", label: "Mango" },
  { slug: "dockers", label: "Dockers" },
  { slug: "steve-madden", label: "Steve Madden" },
  { slug: "timberland", label: "Timberland" },
  { slug: "crocs", label: "Crocs" },
  { slug: "ugg", label: "UGG" },
  { slug: "amazfit", label: "Amazfit" },
  { slug: "vionic", label: "Vionic" },
  { slug: "birkenstock", label: "Birkenstock" },
  { slug: "carolina-herrera", label: "Carolina Herrera" },
  { slug: "brixton", label: "Brixton" },
  { slug: "giuseppe-zanotti", label: "Giuseppe Zanotti" },
  { slug: "rowe-and-taylor", label: "Rowe and Taylor" },
  { slug: "bloomingdales", label: "Bloomingdale's" },
  { slug: "tory-burch", label: "Tory Burch" },
  { slug: "maceoo", label: "Maceoo" },
  { slug: "vy-jewelry", label: "VY Jewelry" },
  { slug: "oakley", label: "Oakley" },
  { slug: "ray-ban", label: "Ray-Ban" },
  { slug: "costa-del-mar", label: "Costa Del Mar" },
  { slug: "tucci", label: "TUCCI" },
  { slug: "bvlgari", label: "Bvlgari" },
  { slug: "lancome", label: "Lancôme" },
  { slug: "sachin-and-babi", label: "Sachin and Babi" },
  { slug: "dream-pairs", label: "Dream Pairs" },
  { slug: "nortiv-8", label: "Nortiv 8" },
  { slug: "bruno-marc", label: "Bruno Marc" },
  { slug: "coofandy", label: "Coofandy" },
  { slug: "kxkshop", label: "KXKshop" },
  { slug: "crazy-shirts", label: "Crazy Shirts" }, 
  { slug: "ecko-unltd", label: "Ecko Unltd" }, 
  { slug: "musinsa", label: "Musinsa" },
  { slug: "dancewear-solutions", label: "Dancewear Solutions" },
  { slug: "marathon-watch", label: "Marathon Watch" },
  { slug: "belle-fare", label: "Belle Fare" },
  { slug: "citizen", label: "Citizen" },
  { slug: "gevril", label: "Gevril" },
  { slug: "hamilton", label: "Hamilton" },
  { slug: "mido", label: "Mido" },
  { slug: "tissot", label: "Tissot" },
  { slug: "zodiac", label: "Zodiac" },
  { slug: "certina", label: "Certina" },
  { slug: "ball", label: "Ball" },
  { slug: "longines", label: "Longines" },
  { slug: "dansko", label: "Dansko" },
  { slug: "ecco", label: "Ecco" },
  { slug: "abeo", label: "ABEO" },
  { slug: "clarks", label: "Clarks" },
  { slug: "mbt", label: "MBT" },
  { slug: "aetrex", label: "Aetrex" },
  { slug: "beautifeel", label: "Beautifeel" },
  { slug: "born", label: "Born" },
  { slug: "earth", label: "Earth" },
  { slug: "keen", label: "Keen" },
  { slug: "mephisto", label: "Mephisto" },
  { slug: "naot", label: "Naot" },
  { slug: "pikolinos", label: "Pikolinos" },
  { slug: "sanita", label: "Sanita" },
  { slug: "sofft", label: "Sofft" },
  { slug: "taos", label: "Taos" },
  { slug: "teva", label: "Teva" },
  { slug: "merrell", label: "Merrell" },
  { slug: "rieker", label: "Rieker" },
  { slug: "propet", label: "Propet" },
  { slug: "walking-cradles", label: "Walking Cradles" },
  { slug: "brooks", label: "Brooks" },
  { slug: "jordan", label: "Jordan" },
  { slug: "asics", label: "Asics" },
  { slug: "hoka", label: "Hoka" },
  { slug: "saucony", label: "Saucony" },
  { slug: "dr-martens", label: "Dr. Martens" },
  { slug: "sperry", label: "Sperry" },
  { slug: "sam-edelman", label: "Sam Edelman" },
  { slug: "toms", label: "TOMS" },
  { slug: "sorel", label: "Sorel" },
  { slug: "naturalizer", label: "Naturalizer" },
  { slug: "lifestride", label: "LifeStride" },
  { slug: "dr-scholls", label: "Dr. Scholl's" },
  { slug: "franco-sarto", label: "Franco Sarto" },
  { slug: "badgley-mishka", label: "American Glamour By Badgley Mishka" },
  { slug: "sam-and-libby", label: "Sam and Libby" },
  { slug: "aerosoles", label: "Aerosoles" },
  { slug: "eurosoft", label: "Eurosoft" },
  { slug: "ryka", label: "Rykä" },
  { slug: "madden-girl", label: "Madden Girl" },
  { slug: "cole-haan", label: "Cole Haan" },
  { slug: "blowfish-malibu", label: "Blowfish Malibu" },
  { slug: "mia", label: "MIA" },
  { slug: "frye-and-co", label: "Frye and Co." },
  { slug: "nunn-bush", label: "Nunn Bush" },
  { slug: "boc", label: "b.o.c" },
  { slug: "taxi", label: "Taxi" },
  { slug: "stacy-adams", label: "Stacy Adams" },
  { slug: "florsheim", label: "Florsheim" },
  { slug: "k-swiss", label: "K-Swiss" },
  { slug: "coconuts", label: "Coconuts" },
  { slug: "bcbg", label: "BCBG" },
  { slug: "reef", label: "REEF" },
  { slug: "dv-dolce-vita", label: "DV Dolce Vita" },
  { slug: "on-running", label: "On" },
  { slug: "gucci", label: "Gucci" },
  { slug: "chanel", label: "Chanel" },
  { slug: "hermes", label: "Hermès" },
  { slug: "rolex", label: "Rolex" },
  { slug: "cartier", label: "Cartier" },
  { slug: "dior", label: "Dior" },
  { slug: "prada", label: "Prada" },
  { slug: "valentino", label: "Valentino" },
  { slug: "balenciaga", label: "Balenciaga" },
  { slug: "saint-laurent", label: "Saint Laurent" },
  { slug: "fendi", label: "Fendi" },
  { slug: "burberry", label: "Burberry" },
  { slug: "patek-philippe", label: "Patek Philippe" },

] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];
export type GenderSlug = (typeof GENDERS)[number]["slug"];
export type BrandSlug = (typeof BRANDS)[number]["slug"];

export function getSubcategories(categorySlug: string) {
  return CATEGORIES.find((c) => c.slug === categorySlug)?.subcategories ?? [];
}